services:
  idna-convert-test:
    container_name: idna-convert-test
    build:
      context: .
    command: >-
      ash -c "composer install
      && php -d pcov.enabled=0 vendor/bin/phpunit
      --display-notices --display-warnings"
    volumes:
    - ./:/app

  idna-convert-infection:
    build:
      context: .
    command: >-
      ash -c "composer install
      && infection --configuration=infection.json5.dist
      --only-covering-test-cases --min-msi=75 --min-covered-msi=75
      --no-progress --no-interaction"
    volumes:
    - ./:/app
