version: '3.1'
services:
  idna-convert-test:
    image: jitesoft/phpunit:8.2
    container_name: idna-convert-test
    command: ash -c "composer install && phpunit -vvv"
    volumes:
      - ./:/app
